export const plural_exclusives = {
    "f / fe exceptions": {
        "roof": "roofs",
        "chief": "chiefs",
        "belief": "beliefs",
        "proof": "proofs",
        "cliff": "cliffs",
        "chef": "chefs",
        "safe": "safes",
        "gulf": "gulfs",
        "handkerchief": "handkerchiefs",
        "handcuff": "handcuffs",
        "hoof": "hoofs",
        "cuff": "cuffs",
        "puff": "puffs",
        "sniff": "sniffs",
        "stuff": "stuffs",
        "turf": "turfs",
        "staff": "staffs",
        "beef": "beefs",
        "grief": "griefs"
    },
    "o exceptions": {
        "photo": "photos",
        "piano": "pianos",
        "video": "videos",
        "radio": "radios",
        "zoo": "zoos",
        "kilo": "kilos",
        "solo": "solos",
        "cello": "cellos",
        "bamboo": "bamboos",
        "soprano": "sopranos",
        "canto": "cantos",
        "kangaroo": "kangaroos",
        "tattoo": "tattoos",
        "studio": "studios",
        "casino": "casinos"
    },
    "plural as same as singular": {
        "deer": "deer",
        "fish": "fish",
        "sheep": "sheep",
        "moose": "moose",
        "species": "species",
        "series": "series",
        "aircraft": "aircraft",
        "crossroads": "crossroads",
        "means": "means",
        "news": "news",
        "bison": "bison",
        "salmon": "salmon",
        "trout": "trout",
        "swine": "swine",
        "cattle": "cattle",
        "pike": "pike",
        "carp": "carp",
        "shrimp": "shrimp",
        "squid": "squid",
        "cod": "cod",
        "barracuda": "barracuda",
        "tuna": "tuna",
        "plankton": "plankton",
        "air": "air",
        "bread": "bread",
        "water": "water",
        "coral": "coral",
        "algae": "algae",
        "data": "data"
    },
    "else exceptions": {
        "foot": "feet",
        "tooth": "teeth",
        "mouse": "mice",
        "louse": "lice",
        "person": "people",
        "child": "children",
        "ox": "oxen",
        "man": "men",
        "woman": "women",
        "goose": "geese",
        "die": "dice",
        "cactus": "cacti",
        "fungus": "fungi",
        "nucleus": "nuclei",
        "focus": "foci",
        "radius": "radii",
        "stimulus": "stimuli",
        "analysis": "analyses",
        "crisis": "crises",
        "thesis": "theses",
        "diagnosis": "diagnoses",
        "oasis": "oases",
        "basis": "bases",
        "appendix": "appendices",
        "index": "indices",
        "matrix": "matrices",
        "vertex": "vertices",
        "vortex": "vortices",
        "axis": "axes"
    }
};